# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - mise lint
    - mise gogen
    - mise test

builds:
  - id: vendor-plugin
    main: ./main.go
    binary: bin/vendor-plugin-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore Windows ARM64 as it's not commonly used
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/Shikachuu/helm-vendor-plugin/cmd.version={{.Version}}
      - -X github.com/Shikachuu/helm-vendor-plugin/cmd.commit={{.Commit}}
      - -X github.com/Shikachuu/helm-vendor-plugin/cmd.date={{.Date}}

archives:
  - formats: [binary]
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

sboms:
  - artifacts: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: Shikachuu
    name: helm-vendor-plugin
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Helm Vendor Plugin {{ .Tag }} ({{ .Date }})

    Install or update this plugin using:
    ```bash
    helm plugin install https://github.com/Shikachuu/helm-vendor-plugin --version {{ .Tag }}
    # or to update
    helm plugin update vendor
    ```
  footer: |
    **Full Changelog**: https://github.com/Shikachuu/helm-vendor-plugin/compare/{{ .PreviousTag }}...{{ .Tag }}
