# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: vendor-plugin

builds:
  - id: vendor-plugin
    main: ./main.go
    binary: bin/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore Windows ARM64 as it's not commonly used
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/Shikachuu/helm-vendor-plugin/cmd.version={{ .Version }}
      - -X github.com/Shikachuu/helm-vendor-plugin/cmd.commit={{ .Commit }}
      - -X github.com/Shikachuu/helm-vendor-plugin/cmd.date={{ .Date }}

archives:
  - formats: [binary]
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

sboms:
  - artifacts: binary
    cmd: trivy
    args:
      - "rootfs"
      - "--format"
      - "spdx-json"
      - "--output"
      - "$document"
      - "$artifact"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: ✨ Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 🐛 Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: ⚡ Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: ♻️ Code Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 📦 Build System
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 📚 Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: ✅ Tests
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: 🔧 Miscellaneous
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 7
    - title: ⏪ Reverts
      regexp: '^.*?revert(\([[:word:]]+\))??!?:.+$'
      order: 8
    - title: Others
      order: 999

release:
  github:
    owner: Shikachuu
    name: helm-vendor-plugin
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Helm Vendor Plugin {{ .Tag }} ({{ .Date }})

    Install or update this plugin using:
    ```bash
    helm plugin install oci://ghcr.io/shikachuu/helm-vendor-plugin:{{ .Version }}
    # or to update
    helm plugin update vendor
    ```
  footer: |
    **Full Changelog**: https://github.com/Shikachuu/helm-vendor-plugin/compare/{{ .PreviousTag }}...{{ .Tag }}
