apiVersion: v1
type: cli/v1
name: vendor
version: 0.2.2
runtime: subprocess
sourceURL: https://github.com/Shikachuu/helm-vendor-plugin
config:
  usage: vendor [command] -f <file>
  ignoreFlags: false
runtimeConfig:
  platformHooks:
    install:
      - command: "$HELM_PLUGIN_DIR/hack/install-binary.sh"
    update:
      - command: "$HELM_PLUGIN_DIR/hack/install-binary.sh"
  platformCommand:
    - command: $HELM_PLUGIN_DIR/bin/vendor-plugin
    - os: windows
      command: ${HELM_PLUGIN_DIR}\bin\vendor-plugin.exe
