name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to release (e.g. v1.3.0)"
        required: true
        type: string
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.tag_name || github.ref }}
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: GPG prepare
        run: |
          base64 -d <<< "${{ secrets.GPG_KEYRING_BASE64 }}" > secring.gpg

      - name: Run GoReleaser
        run: |
          goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ inputs.tag_name || github.ref_name }}

      - name: Package OCI artifact
        run: |
          bash hack/helm-package.sh
        env:
          HELM_KEY_PASSPHRASE: ${{ secrets.HELM_KEY_PASSPHRASE }}
          SIGNING_KEY_EMAIL: ${{ secrets.SIGNING_KEY_EMAIL }}

      - name: Release OCI plugins with ORAS
        run: |
          TAG="${{ inputs.tag_name || github.ref_name }}"
          VERSION="${TAG#v}"
          # oras will include the full path to the artifact files, we must cd into the directory
          cd dist
          # upload the plugins to github's oci registry, the file names AND the repo name MUST match the plugin name in the plugin.yaml file!
          oras push "$NAME:$VERSION" \
            --artifact-type application/vnd.helm.plugin.v1+json \
            "helm-vendor-plugin-${VERSION}.tgz" \
            "helm-vendor-plugin-${VERSION}.tgz.prov"

          oras push "$NAME:latest" \
            --artifact-type application/vnd.helm.plugin.v1+json \
            "helm-vendor-plugin-${VERSION}.tgz" \
            "helm-vendor-plugin-${VERSION}.tgz.prov"
        env:
          NAME: "ghcr.io/shikachuu/helm-vendor-plugin"
